---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-sample
  namespace: staging
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-sample 
